.conf/Dockerfile
.conf/notice-registration.md
.github/workflows/build.yml
.github/workflows/release-release_candidate.yml
.github/workflows/release.yml
.github/workflows/release_candidate.yml
README.md

- enable workflows for push to dockerhub
- change to tags from docker metadata action
- add notice for docker images and license in readme https://github.com/eclipse-tractusx/portal-frontend-registration/issues/17
- remove references to consortia envs from readme
- remove temporary security fixes
https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-05
https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-06

build: enable push to dockerhub 

---

src/components/AboutCard.tsx

remove space after commit id text
space is not necessary
NA

fix(legal-notice): remove space between commit id and colon

---

.github/workflows/dependencies.yaml
.github/workflows/release.yml
DEPENDENCIES
NOTICE.md
scripts/check-dependencies.md

- add workflow to check 3rd party dependencies with the [Eclipse Dash License Tool](https://github.com/eclipse/dash-licenses)
- change dependencies file to '-summary' format from Dash Tool
**Due to the new format in the dependencies file: once this PR is merged into dev, all open feature branches should be rebased to dev, as the dependencies check will fail otherwise.**
- skip dispatch to portal-cd for hotfix in the release workflow
- update notice file
Dependencies check should be automated
Hotfix scenario not yet covered by release workflow
Notice file needs to be update due to new shared components repository
n/a

chore(workflows): add dependencies check and update release

---

DEPENDENCIES
src/locales/en/translations.json

Removed "/n" from the translation files
/n was used for line break and needed to get removed since the line break currently works with new translation key only
Defect recognized in the testing phase

chore: update translations.json

---

.github/workflows/build.yml
.github/workflows/release-release_candidate.yml
.github/workflows/release.yml
.github/workflows/release_candidate.yml
DEPENDENCIES

build images also for arm64, in addition to amd64
enable localdev umbrella chart: arm64 images needed for usage on Mac
[localdev](https://github.com/eclipse-tractusx/portal-cd/pull/90)

build(arch): build images for arm64

---

src/components/verifyRegistration.tsx

Fix submit button activation logic
UI Enhancement
n/a

fix(submit btn): fix submit btn activation logic

---

DEPENDENCIES
package.json
src/helpers/HttpClient.ts
src/services/RequestService.ts
src/state/features/applicationDocuments/api.ts
src/types/MainTypes.ts
yarn.lock

upgrade axios dependency from 0.27.2 to v1.6.1 and implement changes due to major version upgrade
due to vulnerability in previous version
https://github.com/eclipse-tractusx/portal-frontend-registration/pull/72 didn't solve the issue

fix(vulnerability): upgrade axios dependency

---

.github/pull_request_template.md
public/index.html
scripts/inject-dynamic-env.sh
src/components/cax-companyData.tsx
src/components/cax-companyRole.tsx
src/components/cax-responsibilities.tsx
src/components/dragdrop.tsx
src/components/finish.tsx
src/components/landing.tsx
src/components/verifyRegistration.tsx

- remove consortia dev env from default env settings for portal-backend and centralidp
- change docs links to new directory structure (and update pr template): introduced with eclipse-tractusx/portal-assets#226
https://github.com/eclipse-tractusx/portal-frontend/issues/445

chore: remove references to consortia envs

---

.github/workflows/build.yml
.github/workflows/checks.yml
.github/workflows/release-release_candidate.yml
.github/workflows/release.yml
.github/workflows/release_candidate.yml

set node version explicitly
https://github.com/eclipse-tractusx/portal-cd/issues/158

chore: set node version explicitly

---

src/helpers/utils.ts

- fixed the company region field to accept the hyphens
Some regions, such as 'DE-BY', are not accepted in this field, which results in failure during BPN creation.
https://github.com/eclipse-tractusx/portal-frontend-registration/issues/121

fix(BPN Creation): Company region field regex modification

---

DEPENDENCIES
package.json
yarn.lock

align keycloak version with centralidp keycloak instance
https://github.com/eclipse-tractusx/portal-iam/issues/62

chore: upgrade keycloak-js dependency to v23.0.7

---

public/index.html
scripts/inject-dynamic-env.sh
src/services/EnvironmentService.ts
src/services/UserService.js

Move hard hard coded values to env config.
Some values like Realm name and ClientIDs were still hard coded and are now configurable.
Related:
- https://github.com/eclipse-tractusx/portal/pull/217
[#502](https://github.com/eclipse-tractusx/portal-frontend/issues/502)

chore(env): move values to config

---

DEPENDENCIES
package.json
yarn.lock

Manually upgraded vulnerable dependency package.
A high vulnerability has been found in webpack-dev-middleware. Upgraded the package to safe version.
Dependabot Alert [#25](https://github.com/eclipse-tractusx/portal-frontend-registration/security/dependabot/25)

fix(deps): upgraded vulnerable dependency

---

DEPENDENCIES
package.json

Change output folder to build/ instead of build/registration/
The ingress controller manages the context root on Kubernetes.
#123

fix(build): fix output folder structure

---

src/components/cax-companyData.tsx
src/components/cax-companyRole.tsx
src/components/cax-responsibilities.tsx
src/components/dragdrop.tsx
src/components/footerButton.tsx
src/components/footerHeadline.tsx
src/components/verifyRegistration.tsx

Reverted defaults from empty string to undefined 
In the process of the framework upgrade some default values have been set to the empty string from before undefined. This caused issues with some api endpoints.
#123
https://github.com/eclipse-tractusx/portal-backend/issues/639

fix(defaults): revert defaults set to empty string

---

CHANGELOG.md
package.json

finalize version 2.0.0 by merge into main
https://github.com/eclipse-tractusx/sig-release/issues/671

build(2.0.0): bump version and update docs

---

.conf/Dockerfile.full
.conf/Dockerfile.prebuilt
.conf/docker-notice-registration.md
.github/dependabot.yml
.github/workflows/build.yml
.github/workflows/dependencies.yaml
.github/workflows/kics.yml
.github/workflows/release-release_candidate.yml
.github/workflows/release.yml
.github/workflows/release_candidate.yml
.github/workflows/trivy-main.yml
CONTRIBUTING.md
DEPENDENCIES
LICENSE_non-code
NOTICE.md

merge latest change from dev in main
retire the dev branch after this merge
https://github.com/eclipse-tractusx/portal/issues/243

chore(dev-flow): merge latest change from dev in main

---

DEPENDENCIES
src/helpers/utils.ts

For consent OSP redirect to portal page instead of overlay
In the portal the dialog has been converted from an overlay to a page. The redirect here was still pointing to the old url
https://github.com/eclipse-tractusx/portal-frontend/issues/907

fix(consent osp): redirect to portal page instead of overlay

---

src/components/cax-companyRole.tsx
src/components/verifyRegistration.tsx

Roles are not updated during the registration process in role selection and data verification steps if the user navigates between steps.
- When completing the registration, on third steps if we select any roles and navigate till last step, where we have selected roles section.
- Now if user navigate back to the third step, made some changes.
- Again navigate to last step, here these roles are not getting updated.
- Navigate back to third step, you will see the old data instead of latest roles.
- This issue is addressed in this MR
Link to Github issue : https://github.com/eclipse-tractusx/portal-frontend-registration/issues/212

fix: update the roles state when user navigate between the steps

---

CHANGELOG.md
src/components/dragdrop.tsx
src/components/dragdropLayout.tsx

- Removed the code that always displays the error message on this screen.
- Error should display only if the validation for the uploaded document failed.
- Registration | Upload Document : Error msg always display on screen even if no doc uploaded.
https://github.com/eclipse-tractusx/portal-frontend-registration/issues/229
Also verified these cases, which works as expected:
1. Upload pdf whose size is more than 1mb
2. Upload jpg, which throw validation msg
3. Upload pdf whose size is within limit. 

fix: remove code that always displays error message on screen

---

src/types/Patterns.test.ts
src/types/Patterns.ts
src/types/testdata/legalentity.ts

Extended pattern with additional currency characters and length adjustment. Tests added.
Min length: 1
Max lenth: 160
Allows " (double quote \x22) to follow back-end implementation.
Allows £$€¥¢ to allow some additional currency symbols that are used in existing companies.
Much longer company names exist than currently allowed.
Example:
https://find-and-update.company-information.service.gov.uk/company/03249311 
88 characters
Refs: eclipse-tractusx/portal#360

feat(legal entity): extended legal entity length

---

CHANGELOG.md
DEPENDENCIES
src/locales/de/translations.json
src/locales/en/translations.json
src/types/Patterns.ts
src/types/testdata/crn.ts

Update Commercial Registration Number pattern for germany:
- Min length to 4
- Max length to 50
- Special characters äüö
- Round braces ()
- dot .
Same extension for worldwide.
Added tests cases for valid german company registration numbers.
Updated error messages.
Some examples of german company registration numbers did not work with old pattern. See 'HRB 42' or 'HRB 209459 B'. Min/max length alligned with worldwide pattern.
German CRN also requires the court name to be regarded unique. This means that much longer identifiers and some additional special characters need to be allowed.
Refs: #190

fix(identifiers): allow for shorter and longer german crn

---

CHANGELOG.md
DEPENDENCIES
src/components/cax-companyData.tsx

- Removed prop from input field that was setting the BPNL on the form without being firstly validated
When a user would insert an invalid BPNL in the autofill field, the BPNL was updating in the form despite being invalid, leading to the possibility of the user submitting the application with an incorrect BPNL. 
#252

fix: remove logic that sets bpn before validation

---

src/components/cax-companyData.tsx

- Updated the logic to handle the missing values if BPN is present
- Data (Postal code, country) is missing for BPN autofill data fields
- https://github.com/eclipse-tractusx/portal-frontend-registration/issues/243

fix: update the logic to handle prefilled values if BPN is present

---

CHANGELOG.md
src/components/cax-companyData.tsx

Fix for bug introduced by me in: eclipse-tractusx/portal-frontend-registration#210
Remove onBlur from radio selection since this invalidated already accepted data.
OnBlur caused issues when receiving multiple identifier via BPDM and invalidated data.
Refs: #190

fix(company data): remove onBlur event handler in radio identifier select

---

CHANGELOG.md
DEPENDENCIES
src/types/Patterns.ts
src/types/testdata/legalentity.ts
tsconfig.json
tsconfig.json.orig

The legal entity pattern now supports and uses letter and currency [unicode categories](https://www.regular-expressions.info/unicode.html).
- Add support of unicode categories via /u option.
- This required update of ecma script to version 6.
International support requires a lot of different languages. Evaluating and reviewing REGEX by using ranges is very hard.
Refs: eclipse-tractusx/portal#360
Dep: eclipse-tractusx/portal-backend#1043

feat(company data): extend legal entity pattern to support all language

---

.github/workflows/trivy-main.yml
.github/workflows/trivy.yml

add "newer" options according to [TRG 8.04](https://eclipse-tractusx.github.io/docs/release/trg-8/trg-8-04)
workflow continuously runs into error: "Path does not exist: trivy-results2.sarif"
https://github.com/eclipse-tractusx/portal/issues/467

chore(trivy): add options according to TRG 8.04

---

.github/workflows/dependencies.yaml

- Modify dependencies check to run only on yarn.lock updates
- Optimize CI by running dependency checks only when yarn.lock changes.
- https://github.com/orgs/eclipse-tractusx/projects/61/views/1?pane=issue&itemId=86504502
#296 

ci: modify dependencies check to run only on yarn.lock updates

---

CHANGELOG.md
src/components/StepHeader.tsx
src/components/cax-companyData.tsx
src/components/cax-companyRole.tsx
src/components/cax-responsibilities.tsx
src/components/dragdrop.tsx
src/components/verifyRegistration.tsx

Moved header code to a separate component.
- To optimize the codebase and eliminate duplication, it is recommended that the header section of each step be extracted into a separate component. 
- Registration processes contain repetitive header code across multiple steps, resulting in redundancy. 
- We can enhance code maintainability and reusability by isolating the header component, streamlining the overall development process.
[Link to Github issue.](https://github.com/eclipse-tractusx/portal-frontend-registration/issues/309)

fix: create a new component for form-header used in each step

---

src/styles/newApp.css

update style of email text to support break word to next line
**Changelog**
**Registration Form**
- fixed email text break word issue
email text is overlapping with button
#303 

fix(registration): break email word to the next line

---

CHANGELOG.md
src/components/cax-companyData.tsx

- Added utf normalisation to all text fields on companyData page
Changelog: 
```
- **Registration Form**
- added utf normalization on form text fields [#367](https://github.com/eclipse-tractusx/portal-frontend-registration/pull/367)
```
There are some cases where umlaut characters are not being validated. This is happening when text is being copy and pasted from a website or a website from certain bowsers that construct umlaut characters by combining two utf characters instead of using the single uft character of that umlaut. 
For example:
U+0075  + U+0308 = Ü  -> Error
U+00FC = Ü -> Accepted 
Therefore, a function is needed to convert cases where two utf codes are used into a single more universally accepted code. 
#365 

fix: add utf normalization on text fields

---

.github/workflows/build.yml
.github/workflows/checks.yml
.github/workflows/release.yml

Add --frozen-lockfile to workflows and add additional check in pr-checks to prevent uncommitted changes.
Prevent de-sync of package.json and yarn.lock. Otherwise unintended package version changes could be included in builds.
#400

ci(yarn): fail install if package changes were not applied
