- CHANGELOG.md
https://jira.catena-x.net/browse/CPLP-1576
> CPLP-1576: Update changelog for 0.6.0

- CHANGELOG.md
https://jira.catena-x.net/browse/CPLP-1401
> CPLP-1401: Add changelog for 0.5.4.1

- CHANGELOG.md
- package.json
- src/components/cax-companyData.tsx
The last merge into main for v1.3.0 was RC2. This PR contains the delta up to the finalization of v1.3.0.
Changes:
- fix country error snackbar
- updated changelog and version
> release: finalize v1.3.0

- CHANGELOG.md
- package.json
merge main in dev for 1.3.1 version. 
to wrap up main in dev for 1.3.1 version. 
n/a
> release(1.3.1): merge main in dev

- CHANGELOG.md
- package.json
- src/App.tsx
- src/components/AboutCard.tsx
- src/components/AboutPage.tsx
- src/components/about.tsx
- src/components/footer.tsx
- src/locales/de/translations.json
- src/locales/en/translations.json
about page and component added. removed all files and texts related to third party libraries
https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-06
NA
> feat(legal-notice) : add about page

- CHANGELOG.md
- src/components/cax-responsibilities.tsx
- src/locales/de/translations.json
- src/locales/en/translations.json
- src/state/features/applicationInviteUser/slice.ts
- src/state/features/applicationInviteUser/types.ts
User Invite handle success or error response
To make it smooth for UI behavior
CPLP-2573
> fix(invite user): handle success and error response

- CHANGELOG.md
- package.json
merge main in dev for 1.4.0-RC1 version.
to wrap up release process for 1.4.0-RC1 version.
n/a
> release(1.4.0-RC1): merge main in dev

- CHANGELOG.md
- src/components/cax-companyRole.tsx
- src/reportWebVitals.ts
Sonar Bugs Fixes
To improve sonar analytics
CPLP-2793
> fix(sonar bugs): add catch statement to promises

- src/helpers/utils.ts
Veracode Bugs Fixes
To improve analytics
CPLP-2693
> fix(veracode): remove bug

- .github/workflows/release.yml
- CHANGELOG.md
- package.json
merge release branch in main for 1.4.0 version.
to wrap up release process for 1.4.0 version.
n/a
> release(1.4.0): merge release in main

- CHANGELOG.md
- package.json
Please include a summary of the change.
Bump the version and update the change log for release v1.5.0-RC2
N/A
> release: bump version for v1.5.0-RC2

- src/components/dragdrop.tsx
- src/locales/de/translations.json
- src/locales/en/translations.json
change file size error message. reduce supported size from 8mb to 1mb
Registration Upload Document Error
NA
> updates(document upload): supported document size

- .github/workflows/trivy-dev.yml
- .github/workflows/trivy.yml
change container registry for trivy scan to Docker Hub.
I forgot to change the container registry as part of https://github.com/eclipse-tractusx/portal-frontend-registration/pull/19
n/a
> chore(trivy): change container registry

- .github/workflows/trivy-dev.yml
- .github/workflows/trivy.yml
- CHANGELOG.md
- DEPENDENCIES
- package.json
Merge release branch  for v1.5.0-RC3 into main
to wrap up release process
N/A
> release(1.5.0-RC3): merge release into main

- .github/workflows/trivy-dev.yml
- .github/workflows/trivy.yml
- CHANGELOG.md
- DEPENDENCIES
- package.json
merge main in dev for 1.5.0-RC3 version.
to wrap up release process for 1.5.0-RC3 version.
n/a
> release(1.5.0-RC3): merge main in dev

- DEPENDENCIES
- package.json
- yarn.lock
Upgrade dependencies.
Upgrading dependencies to the latest versions is a routine process.
ref. Jira CPLP2995
> chore(deps): upgrade dependencies

- LICENSES/CC-BY-4.0.txt
- public/Catena-X_Logo_mit_Zusatz_2021.svg.license
- public/ID_Card.png.license
- public/logo_cx.svg.license
- public/mail.png.license
- public/tick.svg.license
- change license notice for images
- add second license
https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-07
n/a
> chore(trg-7-07): change license notice for images

- CHANGELOG.md
- package.json
- src/components/rolesError.tsx
- bump version
- update changelog
- add file headers https://github.com/eclipse-tractusx/portal-frontend-registration/issues/54
to prepare the release branch for the latest release
N/A
> release: finalize v1.5.0-RC5

- .tractusx
- CHANGELOG.md
- package.json
Merge release branch  for v1.5.0-RC5 into main
to wrap up release process
N/A
> release(1.5.0-RC5): merge release into main

- src/types/Patterns.test.ts
- src/types/Patterns.ts
updated pattern to include šá characters in organization address
To allow specified special characters for address 
Ref: TEST-1255
> fix(company data): update address

- NOTICE.md
- public/Catena-X_Logo_mit_Zusatz_2021.svg.license
- public/logo_cx.svg.license
attribute logos in notice
[third-party-content](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-07#third-party-content)
n/a
> chore: attribute CX logo

- CHANGELOG.md
- NOTICE.md
- package.json
- public/Catena-X_Logo_mit_Zusatz_2021.svg.license
- public/logo_cx.svg.license
Merge release branch  for v1.5.0 into main
to wrap up release process
N/A
> release(1.5.0): merge release into main 

- CHANGELOG.md
- src/components/cax-companyData.tsx
- src/components/cax-companyRole.tsx
- src/components/cax-responsibilities.tsx
- src/components/dragdrop.tsx
- src/components/finish.tsx
- src/components/footerButton.tsx
- src/components/footerHeadline.tsx
- src/components/landing.tsx
- src/components/verifyRegistration.tsx
updated help links with valid help page content
To get valid help section
Ref: TEST-1428
> bugfix(form): updated help links

- DEPENDENCIES
- package.json
- yarn.lock
for axios and css-what
vulnerabilities in dependencies
npm/npmjs/@babel/traverse/7.23.3.
https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/11520
npm/npmjs/@babel/types/7.23.3.
https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/11521
npm/npmjs/@babel/generator/7.23.3.
https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/11522
> fix(vulnerabilities): set resolutions

- DEPENDENCIES
- package.json
- src/components/verifyRegistration.tsx
- yarn.lock
Fix the broken build
Build was broken from some previous commit.
n/a
> fix(build): repair broken build

- .github/workflows/trivy-dev.yml
- .github/workflows/trivy.yml
- CHANGELOG.md
- DEPENDENCIES
- package.json
- src/components/AboutCard.tsx
- src/components/about.tsx
- src/components/button.tsx
- src/components/cax-companyData.tsx
- src/components/cax-companyRole.tsx
- src/components/cax-header.tsx
- src/components/cax-registration.tsx
- src/components/dragdrop.tsx
- src/components/dragdropFiles.tsx
- src/components/rolesError.tsx
- src/components/verifyRegistration.tsx
- src/helpers/HttpClient.ts
- src/services/RequestService.ts
- src/types/MainTypes.ts
- yarn.lock
Merge the latest release changes from v1.5.3 into main
to have the latest changes of v1.5.3 available in the main branch
N/A
> release(1.5.3): merge release into main

- CHANGELOG.md
- src/components/verifyRegistration.tsx
updated verify registration help link with valid link
To add valid link
Ref: TEST-1450
> fix(verify step): update help link

- CHANGELOG.md
- DEPENDENCIES
- src/components/cax-companyData.tsx
- src/components/cax-companyRole.tsx
Error handling in step 1 on click of confirm and consent data changes in step 3
UI Enhancements
n/a
> feat(consent data): step 1 error handling and consent data changes

- public/index.html
- src/components/landing.tsx
- src/services/EnvironmentService.ts
- src/state/utils/rtkUtil.ts
Remove unused code and make use of asset base function
Code Improvements
n/a
> fix(unused code): remove unused code and add asset base fn to fetch image

- .github/workflows/checks.yml
- .vscode/settings.json
- DEPENDENCIES
- package.json
- yarn.lock
- upgrade dependencies for vulnerabilities in axios, follow-redirects, postcss, @adobe/css-tools and serialize-javascript
- add build check at pull request
- update file header template
> chore: fix dependencies and add build check at pull request

- CHANGELOG.md
- package.json
- src/components/verifyRegistration.tsx
Merge all related release changes to main
To have the latest changes available in main
N/A
> build(1.6.0-RC2): merge release into main

- .github/pull_request_template.md
- CHANGELOG.md
- package.json
- public/index.html
- scripts/inject-dynamic-env.sh
- src/components/Snackbar/index.tsx
- src/components/cax-companyData.tsx
- src/components/cax-companyRole.tsx
- src/components/cax-registration.tsx
- src/components/cax-responsibilities.tsx
- src/components/dragdrop.tsx
- src/components/finish.tsx
- src/components/landing.tsx
- src/components/verifyRegistration.tsx
- src/locales/de/translations.json
- src/locales/en/translations.json
Merge all related release changes to main
To have the latest changes available in main
N/A
> build(1.6.0-RC3): merge release into main

- CHANGELOG.md
- src/components/cax-companyData.tsx
- src/state/features/application/applicationApiSlice.ts
Change country input to select list in step1
UI Improvements
n/a
> feat(step1): change country input to select

- src/components/cax-companyData.tsx
Fix country not display issue
For new user not having default value so was not showing country list
n/a
> feat(step1): fix default empty value issue

- CHANGELOG.md
- package.json
* update changelog for v1.6.0-RC4
* bump version for v1.6.0-RC4
to have the latest changes available in the changelog
[#166](https://github.com/eclipse-tractusx/portal-cd/issues/166)
> build: bump version for v1.6.0-RC4

- CHANGELOG.md
- src/components/cax-companyData.tsx
Add asterisk to identifier type
UI Improvements
https://github.com/eclipse-tractusx/portal-frontend-registration/issues/103
> fix(identifier type): add asterisk

- CHANGELOG.md
- DEPENDENCIES
- package.json
- yarn.lock
Logout redirect issue fix
Updated Keycloak package solved this issue
https://github.com/eclipse-tractusx/portal-frontend-registration/issues/102
> fix(logut): fixed logout redirect issue 

- CHANGELOG.md
- DEPENDENCIES
- package.json
- src/components/cax-companyData.tsx
- yarn.lock
[#167](https://github.com/eclipse-tractusx/portal-cd/issues/167)
> build(1.6.0-RC5): merge release into main

- .github/workflows/build.yml
- .github/workflows/release-release_candidate.yml
- .github/workflows/release.yml
- .github/workflows/release_candidate.yml
- .tractusx
- NOTICE.md
- README.md
change portal-cd references to portal
TRG-2.04 compliance
https://github.com/eclipse-tractusx/portal-cd/issues/131
> chore(trg-2.04): change portal-cd references to portal

- CHANGELOG.md
- src/helpers/utils.ts
- src/types/Patterns.ts
update pattern to support special characters in registration form
support special char
#104 
> fix(registration form): update pattern

- .github/workflows/build.yml
- .github/workflows/release-release_candidate.yml
- .github/workflows/release.yml
- .github/workflows/release_candidate.yml
- .tractusx
- CHANGELOG.md
- FILEHEADER.md
- NOTICE.md
- README.md
- package.json
- scripts/check-dependencies.md
https://github.com/eclipse-tractusx/portal-cd/issues/188
> build(1.6.0): merge release into main

- .github/workflows/build.yml
- .github/workflows/release-release_candidate.yml
- .github/workflows/release.yml
- .github/workflows/release_candidate.yml
- .tractusx
- CHANGELOG.md
- FILEHEADER.md
- NOTICE.md
- README.md
- package.json
- scripts/check-dependencies.md
Merge the latest changes to the dev branch
To have the latest changes available in the dev branch
[188 ](https://github.com/eclipse-tractusx/portal-cd/issues/188)
> build(1.6.0): merge main into dev

- .github/workflows/build.yml
- .github/workflows/checks.yml
- .github/workflows/release-release_candidate.yml
- .github/workflows/release.yml
- .github/workflows/release_candidate.yml
- DEPENDENCIES
chore: fix node setup step
Introduced due to https://github.com/eclipse-tractusx/portal/issues/225
https://github.com/eclipse-tractusx/portal-shared-components/issues/132
> chore: fix node setup step

- DEPENDENCIES
update dependencies file
https://github.com/eclipse-tractusx/portal-frontend-registration/pull/142
follow up to https://github.com/eclipse-tractusx/portal-frontend-registration/issues/123
> chore: update dependencies file

- CHANGELOG.md
- DEPENDENCIES
- src/components/cax-companyRole.tsx
- src/state/features/applicationCompanyRole/applicationCompanyRoleApiSlice.ts
Support optional agreements for company role
To support optional agreements with validation
https://github.com/eclipse-tractusx/portal-frontend-registration/issues/130
> feat(company role): support optional agreements

- CONTRIBUTING.md
- DEPENDENCIES
- LICENSE_non-code
- NOTICE.md
- update licensing and legal docs
#185
> chore(TRG-7): update licensing and legal docs

- .github/dependabot.yml
- .github/workflows/build.yml
- .github/workflows/dependencies.yaml
- .github/workflows/kics.yml
- .github/workflows/release.yml
- .github/workflows/trivy-main.yml
- DEPENDENCIES
get rid of dev branch: adjust workflows
https://github.com/eclipse-tractusx/portal/issues/243
> chore(dev-flow): maintain latest changes in main branch

- CHANGELOG.md
- package.json
https://github.com/eclipse-tractusx/portal/issues/350
> build(2.0.1-rc1): merge main into main

- CHANGELOG.md
- DEPENDENCIES
- package.json
- yarn.lock
https://github.com/eclipse-tractusx/portal/issues/350
> build(2.0.1-rc2): merge main into main

- CHANGELOG.md
- package.json
https://github.com/eclipse-tractusx/portal/issues/379
> build(2.0.1): bump version and update docs

- .github/workflows/trufflehog.yml
- DEPENDENCIES
add trufflehog secret scan
https://github.com/eclipse-tractusx/portal/issues/397
> ci: add trufflehog secret scan

- CHANGELOG.md
- package.json
https://github.com/eclipse-tractusx/portal/issues/433
> build(2.1.0-alpha.1): merge release into main

- DEPENDENCIES
- yarn.lock
Upgrade dependent libraries
Regular procedure to get latest bugfixes.
#258
> chore: upgrade app dependencies

- CHANGELOG.md
- package.json
finalize version 2.1.0-RC1 by merge into main
https://github.com/eclipse-tractusx/portal/issues/465
> build(2.1.0-RC1): bump version and update docs

- .github/workflows/dependencies.yaml
- DEPENDENCIES
Also trigger dependencies.yaml workflow on changes to dependencies.yaml and DEPENDENCIES file.
Prevent wrong/accidental changes to DEPENDENCIES file. Improvement to changes in eclipse-tractusx/portal-frontend-registration#300.
Refs: eclipse-tractusx/portal-frontend-registration#296
> ci: modify dependencies check to run on DEPENDENCIES updates

- CHANGELOG.md
- package.json
https://github.com/eclipse-tractusx/portal/issues/482
> build(2.1.0): bump version and update docs 

- CHANGELOG.md
Update CHANGELOG.md for 2.1.0-RC1
Release 2.1.0-RC1
Refs: eclipse-tractusx/portal#502
> chore(2.1.1-RC1): update changelog

- DEPENDENCIES
- package.json
- yarn.lock
upgrade axios dependency
dependabot
https://github.com/eclipse-tractusx/portal/issues/524
> build: upgrade axios dependency

- .github/workflows/dependencies.yaml
- CHANGELOG.md
- DEPENDENCIES
- package.json
- yarn.lock
finalize version 2.2.0-RC1 by merge into main
https://github.com/eclipse-tractusx/portal/issues/524
> build(2.2.0-RC1): bump version and update docs

- package.json
Merge the latest changes in the main branch
https://github.com/eclipse-tractusx/portal/issues/524
> build(2.2.0): bump version

- CHANGELOG.md
Update CHANGELOG.md for 2.2.1-RC1
Release 2.2.1-RC1
Refs: eclipse-tractusx/portal#541
> chore(2.2.1-RC1): update changelog

- package.json
Merge v2.2.1-RC1 into main
Update main branch with latest changes
https://github.com/eclipse-tractusx/portal/issues/541
> build(v2.1.1-RC1): merge release into main

- CHANGELOG.md
- package.json
Merge the latest changes in the main branch
https://github.com/eclipse-tractusx/portal/issues/548
> build(2.2.1): bump version and update docs
